SRC@src := \
	src/main.c \
	src/asset_manager/asset_manager_load_assets.c \
	src/asset_manager/asset_manager_free_assets.c \
	src/asset_manager/asset_manager_create.c \
	src/vecmath/vec_dot.c \
	src/vecmath/vec_cross.c \
	src/vecmath/vec_normalize.c \
	src/vecmath/vec_rotate.c \
	src/vecmath/vec_length.c \
	src/parser/parse_cub_file.c \
	src/parser/validate_file_extension.c \
	src/check_map/check_map.c \
	src/check_map/validate_map_char.c \
	src/render/color/color_get_component.c \
	src/render/color/color_multiply_components.c \
	src/render/color/color_create.c \
	src/render/color/color_parse.c \
	src/render/graphics/image_fill_pixel.c \
	src/render/graphics/image_fill.c \
	src/render/graphics/brush_square.c \
	src/render/graphics/image_draw_circle.c \
	src/render/graphics/image_fill_rect.c \
	src/render/graphics/brush_circle.c \
	src/render/graphics/image_draw_line.c \
	src/render/graphics/image_draw_brush.c \
	src/render/graphics/image_draw_rect.c \
	src/render/graphics/image_fill_circle.c \
	src/render/image/image_get_pixel.c \
	src/render/image/image_destroy.c \
	src/render/image/image_load_xpm_file.c \
	src/render/image/image_create.c \
	src/render/window/window_create.c \
	src/render/window/window_destroy.c \
	src/render/window/window_draw_image.c \
	src/map/map_push_char.c \
	src/map/map_destroy.c \
	src/map/map_add_line.c \
	src/map/map_create.c \
	src/map/map_print.c \
	src/map/map_get.c \
	src/map/map_push_line.c \
